-- TABLES AND SEQUNCES REMOVAL
-- Indexes and triggers will be removed as well

DROP TABLE MODA4.CZESC CASCADE CONSTRAINTS;
DROP TABLE MODA4.CZLONEK_ZESPOLU CASCADE CONSTRAINTS;
DROP TABLE MODA4.CZYNNOSC CASCADE CONSTRAINTS;
DROP TABLE MODA4.HARMONOGRAM CASCADE CONSTRAINTS;
DROP TABLE MODA4.KLIENT CASCADE CONSTRAINTS;
DROP TABLE MODA4.KSIAZKA_SERWISOWA CASCADE CONSTRAINTS;
DROP TABLE MODA4.POJAZD CASCADE CONSTRAINTS;
DROP TABLE MODA4.POZYCJA_ZAMOWIENIA CASCADE CONSTRAINTS;
DROP TABLE MODA4.PRACOWNIK CASCADE CONSTRAINTS;
DROP TABLE MODA4.RODZAJ_STANOWISKA CASCADE CONSTRAINTS;
DROP TABLE MODA4.SPECJALIZACJA CASCADE CONSTRAINTS;
DROP TABLE MODA4.SPECJALIZACJA_PRACOWNIKA CASCADE CONSTRAINTS;
DROP TABLE MODA4.STANOWISKO CASCADE CONSTRAINTS;
DROP TABLE MODA4.USLUGA CASCADE CONSTRAINTS;
DROP TABLE MODA4.USZKODZENIE CASCADE CONSTRAINTS;
DROP TABLE MODA4.ZAMOWIENIE CASCADE CONSTRAINTS;
DROP TABLE MODA4.ZESPOL CASCADE CONSTRAINTS;

DROP SEQUENCE MODA4.CZYNN_ID_SEQ;
DROP SEQUENCE MODA4.KLIENT_ID_SEQ;
DROP SEQUENCE MODA4.KSIAZ_ID_SEQ;
DROP SEQUENCE MODA4.PRACOW_ID_SEQ;
DROP SEQUENCE MODA4.ZESPOL_ID_SEQ;

--PURGE RECYCLEBIN;  -- Clean recycle bin