-- INSERTING DATA INTO DATABASE
-- in the right order

Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0407151C','Wahacz przedni lewy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0407152C','Wahacz przedni prawy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0501529G','Wahacz tylny lewy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0501530G','Wahacz tylny prawy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('552102G100','Wahacz tylny lewy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('552202G100','Wahacz tylny prawy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0422811B','Końcówka drążka kierowniczego lewa',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0422812B','Końcówka drążka kierowniczego prawa',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('8N0601025A','Felga aluminiowa 16"',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('G052167M4','Olej silnikowy 5W-30',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('G013A8J1G','Płyn chłodniczy G13',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0129620','Filtr powietrza',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('04E115561H','Filtr oleju',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0819644A','Filtr kabinowy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0698451F','Klocki hamulcowe przednie',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0615301AA','Tarcza hamulcowa przednia',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('038103483E','Uszczelka pokrywy zaworów',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0919051D','Pompa paliwowa',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('038103383M','Uszczelka głowicy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0853855','Próg lewy',null);
Insert into CZESC (NR_OEM,NAZWA,OPIS) values ('1J0853856','Próg prawy',null);

Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Kowalski','Jan','500123456','jan.kowalski1990@gmail.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Nowak','Anna','600234567','anna.nowak@poczta.onet.pl','Kontaktować się mailowo lub sms.');
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Wiśniewski','Michał','502345678','mwisniewski95@gmail.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Nowakowski','Robert','513345678',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Lewandowski','Krzysztof','507789012',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Zielińska','Ewa','603456789','ewa.zielinska@mail.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Szymański','Paweł','504567890','pawels02145@wp.pl',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Wójcik','Karolina','505678901',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Kaczmarek','Jacek','508890123',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Jabłoński','Tomasz','509901234','tomasz.jablonski@outlook.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Król','Monika','510012345','monika.kol@wp.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Piotrowski','Adam','511123456',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Adamczak','Agnieszka','412234567','agaadamczak@tlen.pl',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Kowalczyk','Kacper','514456789','kowalczyk123k@gmail.com',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Kowalski','Jakub','515567890','jakub.kowalski@poczta.fm',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Guzik','Jan','716678901','guziczek1985@wp.pl',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Stolarz','Łukasz','517789012',null, null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Zawisza','Andrzej','518890123','andrzej.zawisza@interia.pl',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Malinowska','Dorota','719901234','dorota.malinowska@poczta.onet.pl',null);
Insert into KLIENT (NAZWISKO,IMIE,NR_TELEFONU,ADRES_EMAIL,UWAGI) values ('Ławniczak','Filip','520012345',null, null);

Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('JTNBK3JF1J3145678','O','Toyota','Corolla','2018');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WVWZZZ1JZXW123456','O','Volkswagen','Golf','2016');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WF0SXXGCBJY345678','O','Ford','Focus','2013');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WBA8C3C51H9743126','O','BMW','320i','2017');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WAUZL98T5FA123456','O','Audi','A4','2020');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WDD1760211J123456','O','Mercedes-Benz','A-Class','2018');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('TMBJD61U9FZ123456','O','Skoda','Octavia','2015');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('VF1BZD20023754897','O','Renault','Clio','2022');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('1FWCZ51A3XH123456','O','Peugeot','308','2018');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('W0L0AHL48H1145678','O','Opel','Astra','2003');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('3C3CFFFAXKT123456','O','Fiat','500','2020');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('JH2PC5010LK123456','M','Honda','CB500F','2020');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('SHHFK8770HU234567','O','Honda','Civic','2008');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('U5YGD53LMMJ123456','O','Kia','Ceed','2019');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('WDB96312345678901','C','Mercedes-Benz','Actros','2018');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('JM1BP2238X1234567','O','Mazda','3','2020');
Insert into POJAZD (NR_VIN,RODZAJ_POJAZDU,MARKA,MODEL,ROCZNIK) values ('KMHGD31RMGU123456','O','Hyundai','i30','2017');

Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Nowicki','Jan','Adam','87092694872','600123456','jan.nowicki2513@gmail.com');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Kaczmarek','Michał','Piotr','78101554715','701234567','michal.kaczmarek@wp.pl');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Sobolewski','Krzysztof',null,'82090235133','602345678',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Zieliński','Tomasz','Robert','95032435832','603456789','zielinskit15@o2.pl');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Jankowski','Paweł','Łukasz','99113057618','604567890',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Wojciechowski','Andrzej',null,'73042718815','605678901',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Piątek','Adam',null,'92090259590','606789012','piatekadam@poczta.onet.pl');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Kowalenko','Volodymyr',null,null,'720123456','volo.kowal@gmail.com');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Malewski','Bartosz','Michał','88091623496','707890123',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Dąbrowski','Jakub','Artur','01212396891','608901234','kkkdabrowski@o2.pl');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Ławniczak','Paweł','Łukasz','72111193137','510123456',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Zawisza','Marta',null,'02311556849','612345678','mzawisza02@outlook.com');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Melnyk','Ivan',null,null,'630234567','ivan.melnyk@ukr.net');
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Majewski','Michał','Piotr','92091123498','713456789',null);
Insert into PRACOWNIK (NAZWISKO,IMIE,DRUGIE_IMIE,PESEL,NR_TELEFONU,ADRES_EMAIL) values ('Ławniczak','Krzysztof','Wojciech','01242025617','614567890',null);

Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('POD','Podnośnik','Stanowisko do większości napraw podwozia, zawieszenia, układu wydechowego i wymiany oleju.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('DIA','Diagnostyka komputerowa','Stanowisko do analizy usterek z wykorzystaniem systemów diagnostyki komputerowej.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('WUL','Wulkanizacja','Stanowisko do wymiany opon, ich naprawy oraz wyważania kół.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('BLH','Blacharnia','Stanowisko do napraw blacharskich, w tym prostowania i spawania elementów karoserii.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('LAK','Lakiernia','Stanowisko do lakierowania i malowania karoserii.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('KLI','Serwis klimatyzacji','Stanowisko do diagnostyki, naprawy i napełniania układu klimatyzacji.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('GEO','Geometria kół','Stanowisko do ustawiania zbieżności kół oraz regulacji zawieszenia.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('ELE','Elektromechanika','Stanowisko do napraw instalacji elektrycznych oraz systemów mechaniczno-elektrycznych.');
Insert into RODZAJ_STANOWISKA (ID_RODZAJU,NAZWA,OPIS) values ('MYJ','Myjnia','Stanowisko do mycia zewnętrznego i wewnętrznego pojazdów.');

Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('MECH_Z','Mechanik Zawieszenia','Zajmuje się naprawami układu zawieszenia, hamulcowego, przeniesienia napędu i kierowniczego.');
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('MECH_S','Mechanik Silnika','Zajmuje się naprawami silnika i układu paliwowego.');
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('WULK','Wulkanizator',null);
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('EMECH','Elektromechanik',null);
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('BLACH','Blacharz',null);
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('LAK','Lakiernik',null);
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('D_SERW','Doradca Serwisowy','Doradza klientom w zakresie napraw, prowadzi dokumentację serwisową.');
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('REC','Recepcjonista','Obsługuje klientów.');
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('KLIM','Serwisant Klimatyzacji','Odpowiada za naprawę i konserwację systemów klimatyzacyjnych.');
Insert into SPECJALIZACJA (ID_SPECJALIZACJI,NAZWA,OPIS) values ('DIAG','Diagnosta','Przeprowadza jazdy testowe w celu wykrycia usterki, korzystając z systemów komputerowych.');


Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('1','BLACH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('1','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('1','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('1','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('2','D_SERW');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('2','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('2','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('3','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('3','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('3','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('4','BLACH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('4','LAK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('5','BLACH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('5','LAK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('5','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('6','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('6','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('6','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('7','D_SERW');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('8','EMECH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('8','KLIM');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('9','EMECH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('9','KLIM');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('10','DIAG');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('10','EMECH');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('11','DIAG');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('12','D_SERW');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('12','REC');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('13','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('13','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('13','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('14','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('14','WULK');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('15','MECH_S');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('15','MECH_Z');
Insert into SPECJALIZACJA_PRACOWNIKA (ID_PRACOWNIKA,ID_SPECJALIZACJI) values ('15','WULK');

Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('POD01','POD','Podnośnik 1','Podnośnik uniwersalny dla różnych napraw.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('POD02','POD','Podnośnik 2','Podnośnik uniwersalny dla różnych napraw.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('POD03','POD','Podnośnik 3','Podnośnik uniwersalny dla różnych napraw.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('POD04','POD','Podnośnik 4','Stanowisko z podnośnikiem do wymiany kół i konserwacji.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('DIA01','DIA','Diagnostyka 1','Stanowisko diagnostyczne z komputerem do analizy usterek.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('DIA02','DIA','Diagnostyka 2','Diagnostyka komputerowa z zaawansowanym sprzętem pomiarowym.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('WUL01','WUL','Wulkanizacja 1','Stanowisko wymiany i naprawy opon.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('WUL02','WUL','Wulkanizacja 2','Wyważanie i montaż kół.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('BLH01','BLH','Blacharnia 1','Naprawa blacharska');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('LAK01','LAK','Lakiernia 1','Lakierowanie elementów nadwozia.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('KLI01','KLI','Serwis klimatyzacji 1','Naprawa i napełnianie układu klimatyzacji.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('GEO01','GEO','Geometria 1','Ustawianie geometrii kół i regulacja zawieszenia.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('ELE01','ELE','Elektromechanika 1','Naprawy instalacji elektrycznej i mechanicznej.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('ELE02','ELE','Elektromechanika 2','Diagnostyka i naprawa alternatorów i rozruszników.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('MYJ01','MYJ','Myjnia 1','Mycie zewnętrzne samochodów.');
Insert into STANOWISKO (NR_STANOWISKA,RODZAJ,NAZWA,OPIS) values ('MYJ02','MYJ','Myjnia 2','Czyszczenie wnętrz i tapicerki.');

Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_KH_P','Wymiana klocków hamulcowych przód',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_KH_T','Wymiana klocków hamulcowych tył',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_TH_P','Wymiana tarcz hamulcowych przód',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_TH_T','Wymiana tarcz hamulcowych tył',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_O_SIL','Wymiana oleju silnikowego','Wymiana zawiera wymianę filtra oleju.');
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_O_SB','Wymiana oleju skrzyni biegów','Jeżeli występuje, wymienia się też filtr.');
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_P_CH','Wymiana płynu chłodniczego',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_C_AC','Wymiana czynnika klimatyzacji',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_OP','Wymiana opon',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('WYW_K','Wyważenie kół',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('N_OP','Naprawa opony',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('P_FEL','Prostowanie felgi',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_KDK','Wymiana końcówek drążków kierowniczych',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_WAH_P','Wymiana wahacza przód',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_WAH_T','Wymiana wahacza tył',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_U_PZAW','Wymiana uszczelki pokrywy zaworów',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('R_L_Z','Regulacja luzów zaworowych',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('D_ZAW','Diagnostyka zawieszenia',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('D_BL','Diagnostyka błędu komputera',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('N_ECU','Naprawa komputera silnika',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_P_P','Wymiana pompy paliwowej',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_UPG','Wymiana uszczelki pod głowicą','W ramach usługi wykonuje się planowanie głowicy.');
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('W_PROG','Wymiana progu',null);
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('LAK_EL_D','Lakierowanie dużego elementu','Elementy takie jak maska, drzwi, dach.');
Insert into USLUGA (KOD_USLUGI,NAZWA,OPIS) values ('LAK_EL_M','Lakierowanie małego elementu','Elementy takie jak obudowa lusterka, klamka, spoiler.');

Insert into ZESPOL (NAZWA, UWAGI) values ('Mechanicy A',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Mechanicy B',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Elektromechnicy A',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Lakiernicy A',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Diagnostycy A',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Wulkanizatorzy A',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Wulkanizatorzy B',null);
Insert into ZESPOL (NAZWA, UWAGI) values ('Blacharze A',null);

Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('1','1');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('1','2');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('1','13');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('2','13');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('2','14');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('2','15');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('3','8');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('4','4');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('4','5');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('5','10');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('5','11');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('6','3');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('6','5');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('6','6');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('7','13');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('7','14');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('8','4');
Insert into CZLONEK_ZESPOLU (ID_ZESPOLU,ID_PRACOWNIKA) values ('8','5');

Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('JTNBK3JF1J3145678','1','2',to_date('2025-01-07 12:15','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 15:30','YYYY-MM-DD HH24:MI'),'120050');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('WVWZZZ1JZXW123456','2','2',to_date('2025-01-07 13:12','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 16:10','YYYY-MM-DD HH24:MI'),'230145');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('WF0SXXGCBJY345678','3','2',to_date('2025-01-07 09:15','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 15:10','YYYY-MM-DD HH24:MI'),'289014');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('WBA8C3C51H9743126','4','7',to_date('2025-01-08 10:10','YYYY-MM-DD HH24:MI'),to_date('2025-01-09 15:05','YYYY-MM-DD HH24:MI'),'180520');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('WAUZL98T5FA123456','5','2',to_date('2025-01-08 11:40','YYYY-MM-DD HH24:MI'),to_date('2025-01-09 15:25','YYYY-MM-DD HH24:MI'),'55412');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('WDD1760211J123456','6','2',to_date('2025-01-08 12:25','YYYY-MM-DD HH24:MI'),null,'189241');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('TMBJD61U9FZ123456','7','7',to_date('2025-01-09 13:30','YYYY-MM-DD HH24:MI'),null,'265500');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('VF1BZD20023754897','8','12',to_date('2025-01-09 14:10','YYYY-MM-DD HH24:MI'),null,'32010');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('1FWCZ51A3XH123456','9','12',to_date('2025-01-10 12:15','YYYY-MM-DD HH24:MI'),null,'100579');
Insert into KSIAZKA_SERWISOWA (NR_VIN,ID_KLIENTA,PRZYJMUJACY,DATA_PRZYJECIA,DATA_WYDANIA,PRZEBIEG) values ('W0L0AHL48H1145678','10','2',to_date('2025-01-10 11:05','YYYY-MM-DD HH24:MI'),null,'320124');

Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('1','Lewe lusterko','Zarysowanie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('2','Maska','Obtarcie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('4','Tylne lewe drzwi','Zarysowanie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('4','Przedni zderzak','Pęknięcie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('4','Prawy reflektor','Pęknięcie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('5','Tylne prawe drzwi','Wgniecenie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('5','Lewe nadkole','Zarysowanie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('6','Tylni zderzak','Wgniecenie');
Insert into USZKODZENIE (ID_WIZYTY,LOKALIZACJA,OPIS) values ('8','Przednia lewa opona','Przebicie');

Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('1','W_O_SIL','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('1','D_BL','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('1','N_ECU','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('2','W_O_SIL','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('2','W_OP','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('2','W_P_CH','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('3','W_OP','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('3','WYW_K','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('4','W_KH_P','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('4','W_KH_T','N',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('4','WYW_K','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('5','WYW_K','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('5','W_P_P','Z',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('6','W_WAH_P','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('6','W_WAH_T','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('7','W_KH_P','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('7','W_KH_T','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('7','W_TH_P','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('7','W_TH_T','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('8','N_OP','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('9','W_KH_P','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('9','W_KH_T','O',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('9','W_TH_P','W',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('9','W_TH_T','W',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('10','W_PROG','W',null);
Insert into CZYNNOSC (ID_WIZYTY, KOD_USLUGI, STATUS, UWAGI) values ('10','LAK_EL_D','O',null);

Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('1','1','POD01',to_date('2025-01-07 13:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 13:30','YYYY-MM-DD HH24:MI'),'1');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('2','5','DIA01',to_date('2025-01-07 13:40','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 14:00','YYYY-MM-DD HH24:MI'),'10');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('3','5','DIA01',to_date('2025-01-07 14:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 14:30','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('4','1','POD02',to_date('2025-01-07 10:15','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 10:30','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('5','6','WUL01',to_date('2025-01-07 12:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 12:30','YYYY-MM-DD HH24:MI'),'3');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('5','6','WUL01',to_date('2025-01-07 13:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 13:10','YYYY-MM-DD HH24:MI'),'3');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('6','2','POD01',to_date('2025-01-08 10:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 11:15','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('7','7','WUL01',to_date('2025-01-07 14:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 14:30','YYYY-MM-DD HH24:MI'),'13');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('8','6','GEO01',to_date('2025-01-07 14:45','YYYY-MM-DD HH24:MI'),to_date('2025-01-07 15:15','YYYY-MM-DD HH24:MI'),'3');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('9','1','POD03',to_date('2025-01-08 14:45','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 14:50','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('10','1','POD03',to_date('2025-01-08 14:50','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 15:30','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('11','6','GEO01',to_date('2025-01-08 15:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 15:30','YYYY-MM-DD HH24:MI'),'3');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('12','7','GEO01',to_date('2025-01-08 15:45','YYYY-MM-DD HH24:MI'),to_date('2025-01-08 16:25','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('13','2','POD01',to_date('2025-01-09 10:00','YYYY-MM-DD HH24:MI'),to_date('2025-01-09 11:30','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('23','2','POD02',to_date('2025-01-10 13:15','YYYY-MM-DD HH24:MI'),to_date('2025-01-10 13:30','YYYY-MM-DD HH24:MI'),'12');
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('24','2','POD02',to_date('2025-01-10 13:30','YYYY-MM-DD HH24:MI'),to_date('2025-01-10 13:40','YYYY-MM-DD HH24:MI'),null);
Insert into HARMONOGRAM (ID_CZYNNOSCI,ID_ZESPOLU,NR_STANOWISKA,POCZATEK_CZYNNOSCI,KONIEC_CZYNNOSCI,ODPOWIEDZIALNY) values ('25','8','POD03',to_date('2025-01-10 13:40','YYYY-MM-DD HH24:MI'),to_date('2025-01-10 13:45','YYYY-MM-DD HH24:MI'),null);

Insert into ZAMOWIENIE (NR_ZAMOWIENIA,DATA_ZAMOWIENIA,STAN,CZY_WEWNETRZNE,UWAGI) values ('25/01/0001',to_date('2025-01-08','YYYY-MM-DD'),'Z','0',null);
Insert into ZAMOWIENIE (NR_ZAMOWIENIA,DATA_ZAMOWIENIA,STAN,CZY_WEWNETRZNE,UWAGI) values ('25/01/0002',to_date('2025-01-08','YYYY-MM-DD'),'O','0',null);
Insert into ZAMOWIENIE (NR_ZAMOWIENIA,DATA_ZAMOWIENIA,STAN,CZY_WEWNETRZNE,UWAGI) values ('25/01/0003',to_date('2025-01-09','YYYY-MM-DD'),'N','0',null);
Insert into ZAMOWIENIE (NR_ZAMOWIENIA,DATA_ZAMOWIENIA,STAN,CZY_WEWNETRZNE,UWAGI) values ('25/01/0004',to_date('2025-01-10','YYYY-MM-DD'),'N','0',null);

Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0407151C','25/01/0001','1','1','1');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0407152C','25/01/0001','2','1','1');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0501529G','25/01/0001','3','1',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0501530G','25/01/0001','4','2','8');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0129620','25/01/0002','1','2','8');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('04E115561H','25/01/0002','2','1','12');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0819644A','25/01/0002','3','1',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0698451F','25/01/0002','4','1','12');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('038103483E','25/01/0002','5','1','20');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0919051D','25/01/0003','1','1','21');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('038103383M','25/01/0003','2','1',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('G052167M4','25/01/0003','3',45.5,null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('G013A8J1G','25/01/0003','4','50',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0853855','25/01/0003','5','1',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('8N0601025A','25/01/0004','1','3',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('G052167M4','25/01/0004','2',20.5,null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('G013A8J1G','25/01/0004','3','30',null);
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('1J0129620','25/01/0004','4','1','23');
Insert into POZYCJA_ZAMOWIENIA (NR_OEM,NR_ZAMOWIENIA,LP,ILOSC,ID_CZYNNOSCI) values ('04E115561H','25/01/0004','5','1','23');