    -- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
    --   at:        2025-01-13 21:39:44 CET
    --   site:      Oracle Database 12c
    --   type:      Oracle Database 12c



    -- predefined type, no DDL - MDSYS.SDO_GEOMETRY

    -- predefined type, no DDL - XMLTYPE

    CREATE TABLE CZESC 
        ( 
        NR_OEM VARCHAR2 (30 CHAR)  CONSTRAINT CZESC_PK PRIMARY KEY , 
        NAZWA  VARCHAR2 (100 CHAR) 
            CONSTRAINT CZESC_NAZWA_NN NOT NULL , 
        OPIS   VARCHAR2 (4000 CHAR) 
        ) 
    ;


    CREATE TABLE CZLONEK_ZESPOLU 
        ( 
        ID_ZESPOLU    NUMBER (5) 
            CONSTRAINT CZLON_ID_ZES_NN NOT NULL , 
        ID_PRACOWNIKA NUMBER (5) 
            CONSTRAINT CZLON_ID_PRAC_NN NOT NULL 
        ) 
    ;
    CREATE INDEX CZLON_PRACOW_FK_IDX ON CZLONEK_ZESPOLU 
        ( 
        ID_PRACOWNIKA ASC 
        ) 
    ;

    ALTER TABLE CZLONEK_ZESPOLU 
        ADD CONSTRAINT CZLON_PK PRIMARY KEY ( ID_ZESPOLU, ID_PRACOWNIKA ) ;

    CREATE TABLE CZYNNOSC 
        ( 
        ID_CZYNNOSCI  NUMBER (12)  CONSTRAINT CZYNN_PK PRIMARY KEY, 
        ID_WIZYTY     NUMBER (10) 
            CONSTRAINT CZYNN_ID_WIZ_NN NOT NULL , 
        KOD_USLUGI    VARCHAR2 (10 CHAR) 
            CONSTRAINT CZYNN_KOD_US_NN NOT NULL , 
        NR_ZAMOWIENIA VARCHAR2 (12 CHAR) , 
        STATUS        CHAR (1 CHAR) DEFAULT 'O' 
            CONSTRAINT CZYNN_STATUS_NN NOT NULL , 
        UWAGI         VARCHAR2 (4000 CHAR) 
        ) 
    ;

    COMMENT ON COLUMN CZYNNOSC.STATUS IS 'Status czynnosci: O - oczekujaca, W - w realizacji, Z - zrealizowana, N - niezrealizowana.' 
    ;
    CREATE INDEX CZYNN_ZAMOW_FK_IDX ON CZYNNOSC 
        ( 
        NR_ZAMOWIENIA ASC 
        ) 
    ;
    CREATE INDEX CZYNN_USLUGA_FK_IDX ON CZYNNOSC 
        ( 
        KOD_USLUGI ASC 
        ) 
    ;
    CREATE INDEX CZYNN_KSIAZK_FK_IDX ON CZYNNOSC 
        ( 
        ID_WIZYTY ASC 
        ) 
    ;

    ALTER TABLE CZYNNOSC 
        ADD CONSTRAINT CZYNN_STATUS_CHK 
        CHECK (STATUS IN ('O', 'W', 'Z', 'N'))
    ;


    CREATE TABLE HARMONOGRAM 
        ( 
        ID_CZYNNOSCI       NUMBER (12) 
            CONSTRAINT HARMON_ID_CZYN_NN NOT NULL , 
        ID_ZESPOLU         NUMBER (5) 
            CONSTRAINT HARMON_ID_ZESP_NN NOT NULL , 
        NR_STANOWISKA      VARCHAR2 (5 CHAR) 
            CONSTRAINT HARMON_NR_STAN_NN NOT NULL , 
        POCZATEK_CZYNNOSCI DATE 
            CONSTRAINT HARMON_POCZATEK_NN NOT NULL , 
        KONIEC_CZYNNOSCI   DATE 
            CONSTRAINT HARMON_KONIEC_NN NOT NULL , 
        ODPOWIDZIALNY      NUMBER (5) 
        ) 
    ;

    COMMENT ON COLUMN HARMONOGRAM.ODPOWIDZIALNY IS 'Pracownik odpowiedzialny za wykonanie czynnosci w danym terminie.' 
    ;
    CREATE INDEX HARMON_STANOW_FK_IDX ON HARMONOGRAM 
        ( 
        NR_STANOWISKA ASC 
        ) 
    ;
    CREATE INDEX HARMON_ZESPOL_FK_IDX ON HARMONOGRAM 
        ( 
        ID_ZESPOLU ASC 
        ) 
    ;
    CREATE INDEX HARMON_PRACOW_FK_IDX ON HARMONOGRAM 
        ( 
        ODPOWIDZIALNY ASC 
        ) 
    ;

    ALTER TABLE HARMONOGRAM 
        ADD CONSTRAINT HARMON_PK PRIMARY KEY ( ID_CZYNNOSCI, POCZATEK_CZYNNOSCI ) ;

    CREATE TABLE KLIENT 
        ( 
        ID_KLIENTA  NUMBER (7)  CONSTRAINT KLIENT_PK PRIMARY KEY , 
        NAZWISKO    VARCHAR2 (50 CHAR) 
            CONSTRAINT KLIENT_NAZW_NN NOT NULL , 
        IMIE        VARCHAR2 (30 CHAR) 
            CONSTRAINT KLIENT_IMIE_NN NOT NULL , 
        NR_TELEFONU VARCHAR2 (15 CHAR) 
            CONSTRAINT KLIENT_NR_TEL_NN NOT NULL , 
        ADRES_EMAIL VARCHAR2 (100 CHAR) , 
        UWAGI       VARCHAR2 (4000 CHAR) 
        ) 
    ;


    CREATE TABLE KSIAZKA_SERWISOWA 
        ( 
        ID_WIZYTY      NUMBER (10)  CONSTRAINT KSIAZK_PK PRIMARY KEY , 
        NR_VIN         CHAR (17 CHAR) 
            CONSTRAINT KSIAZK_NR_VIN_NN NOT NULL , 
        ID_KLIENTA     NUMBER (7) 
            CONSTRAINT KSIAZK_ID_KL_NN NOT NULL , 
        PRZYJMUJACY    NUMBER (5) 
            CONSTRAINT KSIAZK_PRZYJ_NN NOT NULL , 
        DATA_PRZYJECIA DATE 
            CONSTRAINT KSIAZK_DATA_NN NOT NULL , 
        DATA_WYDANIA   DATE , 
        PRZEBIEG       NUMBER 
            CONSTRAINT KSIAZK_PRZEB_NN NOT NULL 
        ) 
    ;

    COMMENT ON COLUMN KSIAZKA_SERWISOWA.PRZYJMUJACY IS 'Id pracownika, ktory przyjmuje pojazd do warsztatu' 
    ;

    COMMENT ON COLUMN KSIAZKA_SERWISOWA.PRZEBIEG IS 'Przebieg w kilometrach (km) zanotowany podczas przyjecia pojazdu' 
    ;
    CREATE INDEX KSIAZK_POJAZD_FK_IDX ON KSIAZKA_SERWISOWA 
        ( 
        NR_VIN ASC 
        ) 
    ;
    CREATE INDEX KSIAZK_KLIENT_FK_IDX ON KSIAZKA_SERWISOWA 
        ( 
        ID_KLIENTA ASC 
        ) 
    ;
    CREATE INDEX KSIAZK_PRACOW_FK_IDX ON KSIAZKA_SERWISOWA 
        ( 
        PRZYJMUJACY ASC 
        ) 
    ;


    CREATE TABLE POJAZD 
        ( 
        NR_VIN         CHAR (17 CHAR)  CONSTRAINT POJAZD_PK PRIMARY KEY , 
        RODZAJ_POJAZDU CHAR (1 CHAR) DEFAULT 'O' 
            CONSTRAINT POJAZD_RODZAJ_NN NOT NULL , 
        MARKA          VARCHAR2 (300 CHAR) 
            CONSTRAINT POJAZD_MARKA_NN NOT NULL , 
        MODEL          VARCHAR2 (300 CHAR) 
            CONSTRAINT POJAZD_MODEL_NN NOT NULL , 
        ROCZNIK        NUMBER (4) 
            CONSTRAINT POJAZD_ROCZ_NN NOT NULL 
        ) 
    ;

    COMMENT ON COLUMN POJAZD.RODZAJ_POJAZDU IS 'Rodzaj pojazdu: O - osobowy, M - motocykl, C - ciezarowy.' 
    ;

    ALTER TABLE POJAZD 
        ADD CONSTRAINT POJAZD_RODZ_CHK 
        CHECK (RODZAJ_POJAZDU IN ('O', 'C', 'M'))
    ;


    CREATE TABLE POZYCJA_ZAMOWIENIA 
        ( 
        NR_OEM        VARCHAR2 (30 CHAR) 
            CONSTRAINT POZYC_NR_OEM_NN NOT NULL , 
        NR_ZAMOWIENIA VARCHAR2 (12 CHAR) 
            CONSTRAINT POZYC_NR_ZAM_NN NOT NULL , 
        LP            NUMBER (4) 
            CONSTRAINT POZYC_LP_NN NOT NULL , 
        ILOSC         NUMBER (7,3) 
            CONSTRAINT POZYC_ILOSC_NN NOT NULL 
        ) 
    ;
    CREATE INDEX POZYC_ZAMOW_FK_IDX ON POZYCJA_ZAMOWIENIA 
        ( 
        NR_ZAMOWIENIA ASC 
        ) 
    ;

    ALTER TABLE POZYCJA_ZAMOWIENIA 
        ADD CONSTRAINT POZYC_PK PRIMARY KEY ( NR_OEM, NR_ZAMOWIENIA ) ;

    CREATE TABLE PRACOWNIK 
        ( 
        ID_PRACOWNIKA NUMBER (5)  CONSTRAINT PRACOW_PK PRIMARY KEY , 
        NAZWISKO      VARCHAR2 (50 CHAR) 
            CONSTRAINT PRACOW_NAZW_NN NOT NULL , 
        IMIE          VARCHAR2 (30 CHAR) 
            CONSTRAINT PRACOW_IMIE_NN NOT NULL , 
        DRUGIE_IMIE   VARCHAR2 (30 CHAR) , 
        PESEL         CHAR (11 CHAR) , 
        NR_TELEFONU   VARCHAR2 (15 CHAR) 
            CONSTRAINT PRACOW_NR_TEL_NN NOT NULL , 
        ADRES_EMAIL   VARCHAR2 (100 CHAR) 
        ) 
    ;



    ALTER TABLE PRACOWNIK 
        ADD CONSTRAINT PRACOW_PESEL_UK UNIQUE ( PESEL ) ;

    CREATE TABLE RODZAJ_STANOWISKA 
        ( 
        ID_RODZAJU CHAR (3 CHAR)  CONSTRAINT RODZST_PK PRIMARY KEY , 
        NAZWA      VARCHAR2 (30 CHAR) 
            CONSTRAINT RODZST_NAZWA_NN NOT NULL , 
        OPIS       VARCHAR2 (4000 CHAR) 
        ) 
    ;



    ALTER TABLE RODZAJ_STANOWISKA 
        ADD CONSTRAINT RODZST_NAZWA_UK UNIQUE ( NAZWA ) ;

    CREATE TABLE SPECJALIZACJA 
        ( 
        ID_SPECJALIZACJI VARCHAR2 (6 CHAR)  CONSTRAINT SPECJA_PK PRIMARY KEY , 
        NAZWA            VARCHAR2 (50 CHAR) 
            CONSTRAINT SPECJA_NAZWA_NN NOT NULL , 
        OPIS             VARCHAR2 (4000 CHAR) 
        ) 
    ;



    CREATE TABLE SPECJALIZACJA_PRACOWNIKA 
        ( 
        ID_PRACOWNIKA    NUMBER (5) 
            CONSTRAINT SPECPR_ID_PR_NN NOT NULL , 
        ID_SPECJALIZACJI VARCHAR2 (6 CHAR) 
            CONSTRAINT SPECPR_ID_SP_NN NOT NULL 
        ) 
    ;
    CREATE INDEX SPECPR_SPEC_FK_IDX ON SPECJALIZACJA_PRACOWNIKA 
        ( 
        ID_SPECJALIZACJI ASC 
        ) 
    ;

    ALTER TABLE SPECJALIZACJA_PRACOWNIKA 
        ADD CONSTRAINT SPECPR_PK PRIMARY KEY ( ID_PRACOWNIKA, ID_SPECJALIZACJI ) ;

    CREATE TABLE STANOWISKO 
        ( 
        NR_STANOWISKA VARCHAR2 (5 CHAR) CONSTRAINT STANOW_PK PRIMARY KEY, 
        RODZAJ        CHAR (3 CHAR) 
            CONSTRAINT STANOW_RODZAJ_NN NOT NULL , 
        NAZWA         VARCHAR2 (30 CHAR) 
            CONSTRAINT STANOW_NAZWA_NN NOT NULL , 
        OPIS          VARCHAR2 (4000 CHAR) 
        ) 
    ;
    CREATE INDEX STANOW_RODZST_FK_IDX ON STANOWISKO 
        ( 
        RODZAJ ASC 
        ) 
    ;

    ALTER TABLE STANOWISKO 
        ADD CONSTRAINT STANOW_NAZWA_UK UNIQUE ( NAZWA ) ;

    CREATE TABLE USLUGA 
        ( 
        KOD_USLUGI VARCHAR2 (10 CHAR)  CONSTRAINT USLUGA_PK PRIMARY KEY , 
        NAZWA      VARCHAR2 (50 CHAR) 
            CONSTRAINT USLUGA_NAZWA_NN NOT NULL , 
        OPIS       VARCHAR2 (4000 CHAR) 
        ) 
    ;


    ALTER TABLE USLUGA 
        ADD CONSTRAINT USLUGA_NAZWA_UK UNIQUE ( NAZWA ) ;

    CREATE TABLE USZKODZENIE 
        ( 
        ID_WIZYTY   NUMBER (10) 
            CONSTRAINT USZKOD_ID_WIZ_NN NOT NULL , 
        LOKALIZACJA VARCHAR2 (50 CHAR) 
            CONSTRAINT USZKOD_LOKAL_NN NOT NULL , 
        OPIS        VARCHAR2 (4000 CHAR) 
        ) 
    ;

    COMMENT ON TABLE USZKODZENIE IS 'Uszkodzenina (wizualne) zaobserwowane podczas przyjecia pojazdu. '
    ;

    COMMENT ON COLUMN USZKODZENIE.LOKALIZACJA IS 'Miejsce wystąpienia uszkodzenia (np. lewe lusterko).' 
    ;
    CREATE INDEX USZKOD_KSIAZK_FK_IDX ON USZKODZENIE 
        ( 
        ID_WIZYTY ASC 
        ) 
    ;

    CREATE TABLE ZAMOWIENIE 
        ( 
        NR_ZAMOWIENIA   VARCHAR2 (12 CHAR)  CONSTRAINT ZAMOW_PK PRIMARY KEY , 
        DATA_ZAMOWIENIA DATE 
            CONSTRAINT ZAMOW_DATA_NN NOT NULL , 
        STAN            CHAR (1 CHAR) 
            CONSTRAINT ZAMOW_STAN_NN NOT NULL , 
        CZY_WEWNETRZNE  CHAR (1 CHAR) 
            CONSTRAINT ZAMOW_CZY_WEWN_NN NOT NULL , 
        UWAGI           VARCHAR2 (4000 CHAR) 
        ) 
    ;

    COMMENT ON COLUMN ZAMOWIENIE.STAN IS 'Stan zamowienia: N - niezrealizowane, O - oczekujace, Z - zrealizowane, A - anulowane.' 
    ;

    COMMENT ON COLUMN ZAMOWIENIE.CZY_WEWNETRZNE IS 'Czy zamówienie realizowane w obrębie warsztatu: 0 - zamówienie zewnętrzne do hurtowni, 1 - zamówienie wewnętrzne do magazynu warsztatu.' 
    ;

    ALTER TABLE ZAMOWIENIE 
        ADD CONSTRAINT ZAMOW_STAN_CHK 
        CHECK (STAN IN ('N', 'O', 'Z', 'A'))
    ;


    ALTER TABLE ZAMOWIENIE 
        ADD CONSTRAINT ZAMOW_WEWN_CHK 
        CHECK (CZY_WEWNETRZNE IN (0, 1))
    ;

    CREATE TABLE ZESPOL 
        ( 
        ID_ZESPOLU NUMBER (5)  CONSTRAINT ZESPOL_PK PRIMARY KEY , 
        NAZWA      VARCHAR2 (30 CHAR) 
            CONSTRAINT ZESPOL_NAZWA_NN NOT NULL , 
        UWAGI      VARCHAR2 (1000 CHAR) 
        ) 
    ;


    ALTER TABLE ZESPOL 
        ADD CONSTRAINT ZESPOL_NAZWA_UK UNIQUE ( NAZWA ) ;

    ALTER TABLE CZLONEK_ZESPOLU 
        ADD CONSTRAINT CZLON_PRACOW_FK FOREIGN KEY 
        ( 
        ID_PRACOWNIKA
        ) 
        REFERENCES PRACOWNIK 
        ( 
        ID_PRACOWNIKA
        ) 
    ;

    ALTER TABLE CZLONEK_ZESPOLU 
        ADD CONSTRAINT CZLON_ZESPOL_FK FOREIGN KEY 
        ( 
        ID_ZESPOLU
        ) 
        REFERENCES ZESPOL 
        ( 
        ID_ZESPOLU
        ) 
    ;

    ALTER TABLE CZYNNOSC 
        ADD CONSTRAINT CZYNN_KSIAZK_FK FOREIGN KEY 
        ( 
        ID_WIZYTY
        ) 
        REFERENCES KSIAZKA_SERWISOWA 
        ( 
        ID_WIZYTY
        ) 
        ON DELETE CASCADE 
    ;

    ALTER TABLE CZYNNOSC 
        ADD CONSTRAINT CZYNN_USLUGA_FK FOREIGN KEY 
        ( 
        KOD_USLUGI
        ) 
        REFERENCES USLUGA 
        ( 
        KOD_USLUGI
        ) 
    ;

    ALTER TABLE CZYNNOSC 
        ADD CONSTRAINT CZYNN_ZAMOW_FK FOREIGN KEY 
        ( 
        NR_ZAMOWIENIA
        ) 
        REFERENCES ZAMOWIENIE 
        ( 
        NR_ZAMOWIENIA
        ) 
    ;

    ALTER TABLE HARMONOGRAM 
        ADD CONSTRAINT HARMON_CZYNN_FK FOREIGN KEY 
        ( 
        ID_CZYNNOSCI
        ) 
        REFERENCES CZYNNOSC 
        ( 
        ID_CZYNNOSCI
        ) 
    ;

    ALTER TABLE HARMONOGRAM 
        ADD CONSTRAINT HARMON_PRACOW_FK FOREIGN KEY 
        ( 
        ODPOWIDZIALNY
        ) 
        REFERENCES PRACOWNIK 
        ( 
        ID_PRACOWNIKA
        ) 
    ;

    ALTER TABLE HARMONOGRAM 
        ADD CONSTRAINT HARMON_STANOW_FK FOREIGN KEY 
        ( 
        NR_STANOWISKA
        ) 
        REFERENCES STANOWISKO 
        ( 
        NR_STANOWISKA
        ) 
    ;

    ALTER TABLE HARMONOGRAM 
        ADD CONSTRAINT HARMON_ZESPOL_FK FOREIGN KEY 
        ( 
        ID_ZESPOLU
        ) 
        REFERENCES ZESPOL 
        ( 
        ID_ZESPOLU
        ) 
    ;

    ALTER TABLE KSIAZKA_SERWISOWA 
        ADD CONSTRAINT KSIAZK_KLIENT_FK FOREIGN KEY 
        ( 
        ID_KLIENTA
        ) 
        REFERENCES KLIENT 
        ( 
        ID_KLIENTA
        ) 
    ;

    ALTER TABLE KSIAZKA_SERWISOWA 
        ADD CONSTRAINT KSIAZK_POJAZD_FK FOREIGN KEY 
        ( 
        NR_VIN
        ) 
        REFERENCES POJAZD 
        ( 
        NR_VIN
        ) 
    ;

    ALTER TABLE KSIAZKA_SERWISOWA 
        ADD CONSTRAINT KSIAZK_PRACOW_FK FOREIGN KEY 
        ( 
        PRZYJMUJACY
        ) 
        REFERENCES PRACOWNIK 
        ( 
        ID_PRACOWNIKA
        ) 
    ;

    ALTER TABLE POZYCJA_ZAMOWIENIA 
        ADD CONSTRAINT POZYC_CZESC_FK FOREIGN KEY 
        ( 
        NR_OEM
        ) 
        REFERENCES CZESC 
        ( 
        NR_OEM
        ) 
    ;

    ALTER TABLE POZYCJA_ZAMOWIENIA 
        ADD CONSTRAINT POZYC_ZAMOW_FK FOREIGN KEY 
        ( 
        NR_ZAMOWIENIA
        ) 
        REFERENCES ZAMOWIENIE 
        ( 
        NR_ZAMOWIENIA
        ) 
        ON DELETE CASCADE 
    ;

    ALTER TABLE SPECJALIZACJA_PRACOWNIKA 
        ADD CONSTRAINT SPECPR_PRACOW_FK FOREIGN KEY 
        ( 
        ID_PRACOWNIKA
        ) 
        REFERENCES PRACOWNIK 
        ( 
        ID_PRACOWNIKA
        ) 
    ;

    ALTER TABLE SPECJALIZACJA_PRACOWNIKA 
        ADD CONSTRAINT SPECPR_SPEC_FK FOREIGN KEY 
        ( 
        ID_SPECJALIZACJI
        ) 
        REFERENCES SPECJALIZACJA 
        ( 
        ID_SPECJALIZACJI
        ) 
    ;

    ALTER TABLE STANOWISKO 
        ADD CONSTRAINT STANOW_RODZST_FK FOREIGN KEY 
        ( 
        RODZAJ
        ) 
        REFERENCES RODZAJ_STANOWISKA 
        ( 
        ID_RODZAJU
        ) 
    ;

    ALTER TABLE USZKODZENIE 
        ADD CONSTRAINT USZKOD_KSIAZK_FK FOREIGN KEY 
        ( 
        ID_WIZYTY
        ) 
        REFERENCES KSIAZKA_SERWISOWA 
        ( 
        ID_WIZYTY
        ) 
        ON DELETE CASCADE 
    ;

    CREATE OR REPLACE TRIGGER FKNTM_CZLONEK_ZESPOLU 
    BEFORE UPDATE OF ID_PRACOWNIKA, ID_ZESPOLU 
    ON CZLONEK_ZESPOLU 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table CZLONEK_ZESPOLU is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_CZYNNOSC 
    BEFORE UPDATE OF ID_WIZYTY, KOD_USLUGI 
    ON CZYNNOSC 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table CZYNNOSC is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_KSIAZKA_SERWISOWA 
    BEFORE UPDATE OF PRZYJMUJACY, NR_VIN, ID_KLIENTA 
    ON KSIAZKA_SERWISOWA 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table KSIAZKA_SERWISOWA is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_POZYCJA_ZAMOWIENIA 
    BEFORE UPDATE OF NR_ZAMOWIENIA, NR_OEM 
    ON POZYCJA_ZAMOWIENIA 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table POZYCJA_ZAMOWIENIA is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_SPECJALIZACJA_PRACOWNIKA 
    BEFORE UPDATE OF ID_SPECJALIZACJI, ID_PRACOWNIKA 
    ON SPECJALIZACJA_PRACOWNIKA 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table SPECJALIZACJA_PRACOWNIKA is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_STANOWISKO 
    BEFORE UPDATE OF RODZAJ 
    ON STANOWISKO 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table STANOWISKO is violated'); 
    END; 
    /

    CREATE OR REPLACE TRIGGER FKNTM_USZKODZENIE 
    BEFORE UPDATE OF ID_WIZYTY 
    ON USZKODZENIE 
    BEGIN 
    raise_application_error(-20225,'Non Transferable FK constraint  on table USZKODZENIE is violated'); 
    END; 
    /

    CREATE SEQUENCE CZYNN_ID_SEQ 
    START WITH 1 
        NOCACHE 
        ORDER ;

    CREATE OR REPLACE TRIGGER CZYNN_ID_TRG 
    BEFORE INSERT ON CZYNNOSC 
    FOR EACH ROW 
    WHEN (NEW.ID_CZYNNOSCI IS NULL) 
    BEGIN 
        :NEW.ID_CZYNNOSCI := CZYNN_ID_SEQ.NEXTVAL; 
    END;
    /

    CREATE SEQUENCE KLIENT_ID_SEQ 
    START WITH 1 
        NOCACHE 
        ORDER ;

    CREATE OR REPLACE TRIGGER KLIENT_ID_TRG 
    BEFORE INSERT ON KLIENT 
    FOR EACH ROW 
    BEGIN 
        :NEW.ID_KLIENTA := KLIENT_ID_SEQ.NEXTVAL; 
    END;
    /

    CREATE SEQUENCE KSIAZ_ID_SEQ 
    START WITH 1 
        NOCACHE 
        ORDER ;

    CREATE OR REPLACE TRIGGER KSIAZ_ID_TRG 
    BEFORE INSERT ON KSIAZKA_SERWISOWA 
    FOR EACH ROW 
    BEGIN 
        :NEW.ID_WIZYTY := KSIAZ_ID_SEQ.NEXTVAL; 
    END;
    /

    CREATE SEQUENCE PRACOW_ID_SEQ 
    START WITH 1 
        NOCACHE 
        ORDER ;

    CREATE OR REPLACE TRIGGER PRACOW_ID_TRG 
    BEFORE INSERT ON PRACOWNIK 
    FOR EACH ROW 
    BEGIN 
        :NEW.ID_PRACOWNIKA := PRACOW_ID_SEQ.NEXTVAL; 
    END;
    /

    CREATE SEQUENCE ZESPOL_ID_SEQ 
    START WITH 1 
        NOCACHE 
        ORDER ;

    CREATE OR REPLACE TRIGGER ZESPOL_ID_TRG 
    BEFORE INSERT ON ZESPOL 
    FOR EACH ROW 
    BEGIN 
        :NEW.ID_ZESPOLU := ZESPOL_ID_SEQ.NEXTVAL; 
    END;
    /



    -- Oracle SQL Developer Data Modeler Summary Report: 
    -- 
    -- CREATE TABLE                            17
    -- CREATE INDEX                            14
    -- ALTER TABLE                             43
    -- CREATE VIEW                              0
    -- ALTER VIEW                               0
    -- CREATE PACKAGE                           0
    -- CREATE PACKAGE BODY                      0
    -- CREATE PROCEDURE                         0
    -- CREATE FUNCTION                          0
    -- CREATE TRIGGER                          12
    -- ALTER TRIGGER                            0
    -- CREATE COLLECTION TYPE                   0
    -- CREATE STRUCTURED TYPE                   0
    -- CREATE STRUCTURED TYPE BODY              0
    -- CREATE CLUSTER                           0
    -- CREATE CONTEXT                           0
    -- CREATE DATABASE                          0
    -- CREATE DIMENSION                         0
    -- CREATE DIRECTORY                         0
    -- CREATE DISK GROUP                        0
    -- CREATE ROLE                              0
    -- CREATE ROLLBACK SEGMENT                  0
    -- CREATE SEQUENCE                          5
    -- CREATE MATERIALIZED VIEW                 0
    -- CREATE MATERIALIZED VIEW LOG             0
    -- CREATE SYNONYM                           0
    -- CREATE TABLESPACE                        0
    -- CREATE USER                              0
    -- 
    -- DROP TABLESPACE                          0
    -- DROP DATABASE                            0
    -- 
    -- REDACTION POLICY                         0
    -- TSDP POLICY                              0
    -- 
    -- ORDS DROP SCHEMA                         0
    -- ORDS ENABLE SCHEMA                       0
    -- ORDS ENABLE OBJECT                       0
    -- 
    -- ERRORS                                   0
    -- WARNINGS                                 0
